server:
  port: 9090

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
      path: /swagger-ui-custom.html
      operationsSorter: method

spring:
  datasource:
    url: jdbc:mysql://localhost/emazon-transaction
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update

  feign:
   client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000

appDescription: "Emazon API"
appVersion: "1.0.0"

